### ISSUE TITLE
Plugin reload command

### ISSUE THREAD

**Issue by MagnoBooter** [hwalker928/DiscordX#9]
**Describe the feature you'd like**
Make the plugin reload its config file(s).

**Additional context**
It would be really nice if DiscordX had a command like "/discordx reload" that would reload the config file.

**Comment by hwalker928** [comment]
Greetings,
Please try out the jar inside of the zip folder found here.
https://github.com/hwalker928/DiscordX/actions/runs/460955830

Kind regards.

**Comment by Jpuf0** [comment]
the command is `/dxreload`, it will reload the config and restart the bot
